#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import sys

arg = sys.argv
arglen = len(sys.argv)

if (arglen!=4):print('\nexample:\n $ youtubecalc [view] [good] [bad]\n');exit()

view=float(arg[1])
good=float(arg[2])
bad=float(arg[3])

if (good==0):good=1
if (bad==0):bad=1

print('高評価スコア%d' % (good/bad))
print('%d人に1人が高評価' % (view/good))
print('%d人に1人が低評価' % (view/bad))
print('反応率%f%%' % (100.0*(good+bad)/view))
